### ISSUE TITLE
HassIO Addon: Config not taken into account?

### ISSUE THREAD

**Issue by thundergreen** [snowzach/rts2p#1]
I just tested your nice addon but unfortuntely my config won't be takeen into account:

It load the standard config but not mine.

![image](https://user-images.githubusercontent.com/13320319/68077384-37e95780-fdc3-11e9-8d04-fdadf0dd3a9a.png)

**Comment by snowzach** [comment]
Sorry, I jibbered up the flags parsing. You should be able to rebuild the add-on and it should work now.

**Comment by thundergreen** [comment]
Cool! Thanks! I'll report back :)

**Comment by thundergreen** [comment]
Works! Thanks a lot!! I will try to play with doods then :)
